# Setup
title:        성장하는 개발자, 조성준
tagline:      iOS Application Developer
baseurl:      ""
paginate:     1
locale:       "kr"

# About/contact
author:
  name:       Juseojo
  url:        https://github.com/juseojo

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
